// <auto-generated />
namespace IEPProjekat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedgradestoaddids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedgradestoaddids));
        
        string IMigrationMetadata.Id
        {
            get { return "201908291757517_changed-grades-to-add-ids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
