// <auto-generated />
namespace IEPProjekat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifiedchannelsclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifiedchannelsclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201909171133589_modified-channels-class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
