// <auto-generated />
namespace IEPProjekat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifiedQuestionClassAddedDateTimesForCreationAndLock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifiedQuestionClassAddedDateTimesForCreationAndLock));
        
        string IMigrationMetadata.Id
        {
            get { return "201908221317357_Modified-Question-Class-Added-DateTimes-For-Creation-And-Lock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
