// <auto-generated />
namespace IEPProjekat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChannelClassPopulatedCanBeModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChannelClassPopulatedCanBeModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201908211408493_ChannelClass-Populated-Can-Be-Modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
