// <auto-generated />
namespace IEPProjekat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcategoriestableAndChangedQuestionsToHaveCategoriesAsFieldInsteadOfStringForCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcategoriestableAndChangedQuestionsToHaveCategoriesAsFieldInsteadOfStringForCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201909021854232_added-categories-tableAndChangedQuestionsToHaveCategoriesAsFieldInsteadOfStringForCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
